apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
 name: api-rules
 namespace: default
 labels: 
      release: prometheus
      
spec: 
  groups: 
  - name: api
    rules:
    - alert: down
      expr: up == 0
      for: 0m 
      labels: 
        severity: critical
      annotations: 
         summary: Prometheus target missing {{$labels.instance}}
        