apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels: 
    job: node-api
    app: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - name: web # name is not required for single-port Services
    port: 3000
    targetPort: 3000
    protocol: TCP